name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: sudo apt-get install build-essential curl git lib32stdc++-9-dev \
           libc6-dev-i386 nodejs npm python3-dev python3-pip
      
    - name: Install dependencies
      run: make
      
    
