name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
  - uses: actions/checkout@v2

  - name: Ndk
  - uses: nttld/setup-ndk@v1
    with:
      ndk-version: r21e
  
    steps:
    - uses: actions/checkout@v3
    
    
      
    
    - name: Install dependencies
      run: make core-android-arm64
      
    
